=== zhengshuyu1996/zhengshuyu1996.github.io/homework/week8/filename.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT catalog (book+)>

  <!ELEMENT book (isbn, title, author_surname, author_forenames, publisher, location, year)>

    <!ELEMENT title (#PCDATA)>

    <!ELEMENT author_forenames (#PCDATA)>

    <!ELEMENT author_surname (#PCDATA)>

    <!ELEMENT publisher (#PCDATA)>

    <!ELEMENT location (city, country)>

      <!ELEMENT city (#PCDATA)>

      <!ELEMENT country (#PCDATA)>

    <!ELEMENT isbn (#PCDATA)>

    <!ELEMENT year (#PCDATA)>

=== zhengshuyu1996/zhengshuyu1996.github.io/homework/week8/books.xml
<?xml version = "1.0"?>
<!-- <?xml-stylesheet type="text/css" href="books.css" ?> -->
<!DOCTYPE rootname SYSTEM "filename.dtd">
<?xml-stylesheet type="text/xsl" href="books.xsl" ?>

<catalog>

  <book>

    <isbn> 0-321-14945-9 </isbn>

    <title> Programming the World Wide Web </title>

    <author_surname> Sebesta </author_surname>

    <author_forenames> Robert W </author_forenames>

    <publisher> Addison Wesley </publisher>

    <location>

      <city> London </city>

      <country> United Kingdom </country>

    </location>

    <year> 2003 </year>

  </book>

</catalog>
